name: Test Backend
###################################
# Required Secret : BACK_ENV, BACK_ORM_CONFIG
###################################
on:
    pull_request:
        branches: [develop]
    workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest
        environment: develop

        steps:
            - uses: actions/checkout@v2

            - name: Install Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '16.x'

            - name: Create ORM Config
              uses: jsdaniell/create-json@1.1.2
              with:
                  name: 'ormconfig.json'
                  json: ${{ secrets.BACK_ORM_CONFIG }}
                  dir: 'back/'

            - name: Create Session Config
              uses: jsdaniell/create-json@1.1.2
              with:
                  name: 'sessionStoreConfig.json'
                  json: ${{ secrets.BACK_SESSION_CONFIG }}
                  dir: 'back/'

            - name: Create Environment File
              run: |
                  echo "${{ secrets.BACK_ENV }}" >> .env
              working-directory: ./back

            - name: Test
              run: | 
                  npm install
                  npm run test
              working-directory: ./back
